# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set version
      run: source version.sh && echo "::set-env name=version::$version"
    - name: Echo version
      run: echo $version
    - name: Install dependencies
      run: sudo apt-get -y install python3-stdeb fakeroot python3-all dh-python lintian

    - name: Build the deb
      run: python3 setup.py --command-packages=stdeb.command bdist_deb
    
    - name: Lint the deb
      run: lintian deb_dist/grub-reboot-picker_$version-1_all.deb
    
    - name: Inspect the deb
      run: dpkg -I deb_dist/grub-reboot-picker_$version-1_all.deb
